mv	./bin/update_episode.py.txt		./bin/update_episode.py
mv	./bin/splunklib/ordereddict.py.txt		./bin/splunklib/ordereddict.py
mv	./bin/splunklib/binding.py.txt		./bin/splunklib/binding.py
mv	./bin/splunklib/six.py.txt		./bin/splunklib/six.py
mv	./bin/splunklib/modularinput/argument.py.txt		./bin/splunklib/modularinput/argument.py
mv	./bin/splunklib/modularinput/script.py.txt		./bin/splunklib/modularinput/script.py
mv	./bin/splunklib/modularinput/utils.py.txt		./bin/splunklib/modularinput/utils.py
mv	./bin/splunklib/modularinput/scheme.py.txt		./bin/splunklib/modularinput/scheme.py
mv	./bin/splunklib/modularinput/input_definition.py.txt		./bin/splunklib/modularinput/input_definition.py
mv	./bin/splunklib/modularinput/validation_definition.py.txt		./bin/splunklib/modularinput/validation_definition.py
mv	./bin/splunklib/modularinput/__init__.py.txt		./bin/splunklib/modularinput/__init__.py
mv	./bin/splunklib/modularinput/event_writer.py.txt		./bin/splunklib/modularinput/event_writer.py
mv	./bin/splunklib/modularinput/event.py.txt		./bin/splunklib/modularinput/event.py
mv	./bin/splunklib/client.py.txt		./bin/splunklib/client.py
mv	./bin/splunklib/data.py.txt		./bin/splunklib/data.py
mv	./bin/splunklib/__init__.py.txt		./bin/splunklib/__init__.py
mv	./bin/splunklib/results.py.txt		./bin/splunklib/results.py
mv	./bin/splunklib/searchcommands/search_command.py.txt		./bin/splunklib/searchcommands/search_command.py
mv	./bin/splunklib/searchcommands/environment.py.txt		./bin/splunklib/searchcommands/environment.py
mv	./bin/splunklib/searchcommands/eventing_command.py.txt		./bin/splunklib/searchcommands/eventing_command.py
mv	./bin/splunklib/searchcommands/decorators.py.txt		./bin/splunklib/searchcommands/decorators.py
mv	./bin/splunklib/searchcommands/streaming_command.py.txt		./bin/splunklib/searchcommands/streaming_command.py
mv	./bin/splunklib/searchcommands/external_search_command.py.txt		./bin/splunklib/searchcommands/external_search_command.py
mv	./bin/splunklib/searchcommands/__init__.py.txt		./bin/splunklib/searchcommands/__init__.py
mv	./bin/splunklib/searchcommands/validators.py.txt		./bin/splunklib/searchcommands/validators.py
mv	./bin/splunklib/searchcommands/internals.py.txt		./bin/splunklib/searchcommands/internals.py
mv	./bin/splunklib/searchcommands/generating_command.py.txt		./bin/splunklib/searchcommands/generating_command.py
mv	./bin/splunklib/searchcommands/reporting_command.py.txt		./bin/splunklib/searchcommands/reporting_command.py
mv	./bin/test/test_match_table.py.txt		./bin/test/test_match_table.py
mv	./bin/test/test_baroc_string_format.py.txt		./bin/test/test_baroc_string_format.py
mv	./bin/test/test_match_table_two.py.txt		./bin/test/test_match_table_two.py
mv	./bin/test/test_baroc_string_format_command.py.txt		./bin/test/test_baroc_string_format_command.py
mv	./bin/test/test_match_table_rex.py.txt		./bin/test/test_match_table_rex.py
mv	./bin/baroc_string_format.py.txt		./bin/baroc_string_format.py
mv	./bin/perf.py.txt		./bin/perf.py
mv	./bin/match_table.py.txt		./bin/match_table.py
mv	./bin/command_match_table_rex.py.txt		./bin/command_match_table_rex.py
mv	./bin/command_match_table.py.txt		./bin/command_match_table.py
mv	./bin/blaggert.py.txt		./bin/blaggert.py
mv	./bin/match_table_new.py.txt		./bin/match_table_new.py
mv	./bin/__init__.py.txt		./bin/__init__.py
mv	./bin/app.py.txt		./bin/app.py
mv	./bin/baroc_string_format_command.py.txt		./bin/baroc_string_format_command.py